<?php
// ------------------------------------------------------------------------------------ //
//                                                                                      //
// Direzione LAvori                                                                //
// Data: 26/10/2017                                                                     //
//                       //
// Autore: SIPAL S.p.A. All rights reserved.                                            //
//                                                                                      //
// ------------------------------------------------------------------------------------ //
// Definizione delle costanti



define('INT_APP_NAME', 'Direzione Lavori 1.0');
define('DB_SERVICE_NAME', 'Direzione lavori');
define('PG_HOST', 'localhost');
define('PG_PORT', '5432');
define('PG_DB', 'sviluppo');
define('PG_USER', 'postgres');
define('PG_PASSWD', 'password');
define('USE_PROTECTION', false);

//PHPMAILER
//define('SMTP_MAIL', 'smtp.sisscpa.it');
//define('USERNAME_AUTH_MAIL', 'no-reply@sisscpa.it');
//define('PASSWORD_AUTH_MAIL', 'iq#26ay5ta');

?>
